# -*- coding: utf-8 -*-
"""
Configuration centralisée pour les analyses INV.
"""

from .inv_features_config import (
    INV_FEATURES,
    MODALITY_PREFIX,
    REDUNDANCY_CORR_THRESHOLD,
    PRUNING_PROTECTED_PAIRS,
    FEATURE_PRIORITY,
    CORE_AUDIO,
    CORE_SPEECH,
    CORE_FACE,
    CORE_GAZE,
    CORE_HL,
    CORE_MAP,
    CORE_RIEDL_COLS,
    AUDIO_ALIAS_PAIRS,
    ID_COLS,
    EXCLUDE_SUFFIXES,
    EXCLUDE_PREFIXES,
    COHESION_COMPONENTS,
    TMS_DIMENSIONS,
    QUESTIONNAIRE_RELIABILITY_DIMENSIONS,
    COHESION_SCORE_COL,
    QUESTIONNAIRE_ANALYSIS_COLS,
    PERFORMANCE_ANALYSIS_COLS,
    PERFORMANCE_EXCLUDED_COLS,
    # INV_EXCLUDED_PREFIXES,
    # INV_EXCLUDED_SUFFIXES,
    # INV_EXCLUDED_SUBSTRINGS,
    SCENARIO_COVARIATE_ONLY,
    CORE_SPEECH_V2,
    CORE_FACE_V2,
    CORE_GAZE_V2,
    CORE_HL_V2,
    CORE_MAP_V2,
    CORE_SPEECH_REPORT,
    CORE_FACE_REPORT,
    CORE_GAZE_REPORT,
    CORE_HL_REPORT,
    CORE_MAP_REPORT,
    RETAINED_INV_FEATURES,
    is_excluded_inv_feature,
    filter_inv_feature_names,
    filter_report_feature_names,
    filter_inv_dataframe,
    keep_questionnaire_analysis_col,
    keep_questionnaire_component_col,
    keep_performance_analysis_col,
    infer_family_from_name,
    get_core_features,
    get_feature_priority,
    get_features_by_family,
    is_redundant,
)

__all__ = [
    "INV_FEATURES",
    "MODALITY_PREFIX",
    "REDUNDANCY_CORR_THRESHOLD",
    "PRUNING_PROTECTED_PAIRS",
    "FEATURE_PRIORITY",
    "CORE_AUDIO",
    "CORE_SPEECH",
    "CORE_FACE",
    "CORE_GAZE",
    "CORE_HL",
    "CORE_MAP",
    "CORE_RIEDL_COLS",
    "AUDIO_ALIAS_PAIRS",
    "ID_COLS",
    "EXCLUDE_SUFFIXES",
    "EXCLUDE_PREFIXES",
    "COHESION_COMPONENTS",
    "TMS_DIMENSIONS",
    "QUESTIONNAIRE_RELIABILITY_DIMENSIONS",
    "COHESION_SCORE_COL",
    "QUESTIONNAIRE_ANALYSIS_COLS",
    "PERFORMANCE_ANALYSIS_COLS",
    "PERFORMANCE_EXCLUDED_COLS",
    # "INV_EXCLUDED_PREFIXES",
    # "INV_EXCLUDED_SUFFIXES",
    # "INV_EXCLUDED_SUBSTRINGS",
    "SCENARIO_COVARIATE_ONLY",
    "CORE_SPEECH_V2",
    "CORE_FACE_V2",
    "CORE_GAZE_V2",
    "CORE_HL_V2",
    "CORE_MAP_V2",
    "CORE_SPEECH_REPORT",
    "CORE_FACE_REPORT",
    "CORE_GAZE_REPORT",
    "CORE_HL_REPORT",
    "CORE_MAP_REPORT",
    "RETAINED_INV_FEATURES",
    "is_excluded_inv_feature",
    "filter_inv_feature_names",
    "filter_report_feature_names",
    "filter_inv_dataframe",
    "keep_questionnaire_analysis_col",
    "keep_questionnaire_component_col",
    "keep_performance_analysis_col",
    "infer_family_from_name",
    "get_core_features",
    "get_feature_priority",
    "get_features_by_family",
    "is_redundant",
]
